name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"

      # - name: Push Tag
      #   # uses: changesets/action@v1
      #   run: |
      #     pnpm tag
      #     /usr/bin/git push origin --tags
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      #     registryUrl: https://marketplace.visualstudio.com
      #     dependencies: false
