name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: 🚀 Release new version
          publish: npx @changesets/cli tag # this will create a new tag and a new release


      # - name: Push Tag
      #   # uses: changesets/action@v1
      #   run: |
      #     pnpm tag
      #     /usr/bin/git push origin --tags
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      #     registryUrl: https://marketplace.visualstudio.com
      #     dependencies: false
